<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="WSMusicaCreditoWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/WSMusicaCreditoWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/WSMusicaCreditoWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://wsmusicacredito/">
    <import location="http://localhost:8080/WS_Musica_Credito/WSMusicaCredito?WSDL" namespace="http://wsmusicacredito/"/>
    <plnk:partnerLinkType name="WSMusicaCreditoLinkType">
        <plnk:role name="WSMusicaCreditoRole" portType="ns:WSMusicaCredito"/>
    </plnk:partnerLinkType>
</definitions>
